In [9]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
import numpy as np
a = np.arange(0,12,2)
print(a)
# Output: [0 2 4 6 8]

[ 0  2  4  6  8 10]


In [13]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
b = a.reshape((2,3))
print("reshaped",b)

reshaped [[ 0  2  4]
 [ 6  8 10]]


In [20]:
arr = np.array([1,2,10,4])
print(np.mean(arr),np.median(arr),np.std(arr))

4.25 3.0 3.491060010942235


In [45]:
a = np.random.rand(10)
print(a)
a = np.random.randint(1,10,size=6)
print(a)

[0.94471684 0.69380986 0.72851099 0.19451593 0.16868659 0.40893968
 0.64687393 0.93012251 0.38010071 0.11323016]
[9 8 1 1 6 5]


In [47]:
ph = input("Enter phone number: ")
otp = np.random.randint(10,size=6)
print("otp: ",otp)


otp:  [8 3 5 6 6 2]
